### ISSUE TITLE
BAY PLAN PROCESSING ERROR. Bay Plan Ref No: BP2019000000000004

### ISSUE THREAD

**Issue by OSMANALI09** [dpcs-dj/Issues#13]
***Description of the bug***
A Shipping Agent (MSC) tried to upload their EDI in PROD for their upcoming vessel yesterday. 
They were able to upload/ submit their EDI file.
But after scrutinising further, we have observed that the File Status appears to be displaying 
«File Processing Error».
The Container Details has not been populated either and displays «No items to show».
But the EDI file got submitted anyway.

Vessel Name: MSC ASYA
Voyage Number: IP929A
Bay Plan Ref No: BP2019000000000004
Berth Application No: BA2019080500848

![BAY PLAN_MSC ASYA_FILE PROCESSING ERROR_07 08 2019](https://user-images.githubusercontent.com/53811457/62648534-ac932e00-b95b-11e9-888e-692e433ae5a8.jpg)

![BAY PLAN_MSC ASYA_CONTAINER DETAILS_07 08 2019](https://user-images.githubusercontent.com/53811457/62648533-abfa9780-b95b-11e9-8991-90cbf4eeb7c9.jpg)

![BAY PLAN_MSC ASYA_SUBMISSION STATUS_07 08 2019](https://user-images.githubusercontent.com/53811457/62648536-ac932e00-b95b-11e9-81f7-5fdca4a72d9b.jpg)

**Comment by sivasreenivas** [comment]
1. Earlier generic errors are displayed in the File Status Remarks which was fixed by migrating the latest UAT XBS component release to PROD environment. **After the XBS prod migration(which was done 07.08.2019 afternoon) now specific error to the EDI failed processing error will be displayed.**

2. Submitting the BAPLIE even if the file failed processing is a BUG which teams are working and try to get the fix to the UAT environment at the earliest. Will update the fix when it will be available to UAT.

**Note: BAPLIE can be rejected by the approver when container details are not available so that SA can re-upload the BAPLIE for approval from concerned terminal.**

**Comment by sivasreenivas** [comment]
Fix has been provided in build v3.8.73, Tested the changes in UAT and provided the screenshot of the same below. Review the same at your end and close the ticket.

![image](https://user-images.githubusercontent.com/53824291/63018750-48fc8980-bea2-11e9-9bfb-9fab6108c43e.png)

![image](https://user-images.githubusercontent.com/53824291/63018800-60d40d80-bea2-11e9-8107-88130cb07001.png)

**Comment by sivasreenivas** [comment]
@Abdirahim0  issue has been fixed in v3.8.73, Please help us to close the ticket or if still issue persists provide the evidence.

**Comment by OSMANALI09** [comment]
The correction has been implemented in UAT environment. The File can NOT be submitted if the File has NOT been processed successfully.
