### ISSUE TITLE
Link to view container gate movement details in container storing order details 

### ISSUE THREAD

**Issue by MohamedCheikh** [dpcs-dj/Issues#20]
Added a link in container details tab in Container storing order to view the container details.

![image](https://user-images.githubusercontent.com/53811852/63076014-50707100-bf3c-11e9-8986-002ab160b5fc.png)

**Comment by sivasreenivas** [comment]
Thanks for raising the ticket for tracking. Integrated the SGTD container gate movement API for shipping agents to view the container details.

http://dctcap.dct.dj:10076/sgtd_backend_api_prod/gate_transaction/container?container=PCIU1200430 

{"container":"PCIU1200430","gkey":226503700,"status":"COMPLETE","stage_ID":"outgate","ctr_TYPE_ID":"2200","ctr_FREIGHT_KIND":"FCL","truckvisitgkey":{"exitedyard":"2019-03-26 21:20:03.38","enteredyard":"2019-03-26 20:26:38.413","tvdtls_GKEY":226503639,"truck_LICENSE_NBR":"526D67"}}

Changes are migrated to UAT and currently unable to access the SGTD URL due to firewall blocking at our end, raised firewall request to security team once unblocked we can test this again to container details in the pop-up

**Comment by sivasreenivas** [comment]
@MohamedCheikh @Abdirahim0 Firewall request has been approved by the security team and able to get the container details via link in the DPCS. After the review please help to close the ticket. 

Container storing order reference id: CONTSTO20190000000021 (draft mode) to view the container gate movement.

**Displaying the Container movement if details exists in SGTD**
![image](https://user-images.githubusercontent.com/53824291/63346830-80fe4380-c35e-11e9-9f65-6f5572ef7929.png)

**Displays no results found if container movement details doesnt exist in SGTD**
![image](https://user-images.githubusercontent.com/53824291/63346940-c02c9480-c35e-11e9-84fc-12320d8ed3d2.png)
